{
	"version": 1542039287,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/fundo.png",
		"images/plataforma-sheet0.png",
		"images/bloco1-sheet0.png",
		"images/bloco2-sheet0.png",
		"images/bloco3-sheet0.png",
		"images/disco-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/particles.png",
		"images/fundomenu.png",
		"images/btnplay-sheet0.png",
		"images/btnclose-sheet0.png",
		"images/btnplay2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/esquerda-sheet0.png",
		"images/plataforma2-sheet0.png",
		"images/bloco4-sheet0.png",
		"images/bloco5-sheet0.png",
		"images/bloco6-sheet0.png",
		"images/fundo2.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"media/266430__xtrgamr__rock-band-the-game-controller-not-an-actual-drumset-foot-pedal.ogg",
		"media/riders on the storm2.ogg",
		"media/241337__seidhepriest__guitar-string-slide-noise.ogg",
		"media/vaias.ogg",
		"media/277021__sandermotions__applause-2.ogg",
		"media/277021__sandermotions__applause-2.m4a",
		"media/meu vídeo.m4a",
		"media/meu vídeo.ogg",
		"media/meu víde.ogg",
		"media/guitarrinha[1].m4a",
		"media/guitarrinha[1].ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}